### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by leonardoaraujosantos** [leonardoaraujosantos/LearnSegmentation#1]
## Introduction
Sometimes during training some image from the input list has the wrong shape
``` python 
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224) # HERE....
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
```

Error trace:
``` bash
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    fire.Fire(TrainModel)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/fire/core.py", line 120, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/fire/core.py", line 358, in _Fire
    component, remaining_args)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/fire/core.py", line 561, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 111, in train
    train_step.run(feed_dict={model_in: xs_train, labels_in: ys_train, model_drop: 0.8})
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1706, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3963, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/leoara01/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (224,224,3) into shape (224,224)
```

## Ideas
* Probably this could be a bug while creating the LMDB
* Some error on LoadTrainBatch

**Comment by leonardoaraujosantos** [comment]
## Investigation
Doing some investigation while opening the LMDB file i've found that one particular item is not the same format (224,224,3)
``` python
    def handle_file_dataset(self, path_train, path_val='', train_perc=0.8, val_perc=0.2, shuffle=True):
        '''Handle loading HDF5 and LMDB files'''

        # Check if validation-set exist if not partition from training
        has_validation = not path_val == ''

        print('LMDB file')
        env = lmdb.open(path_train, readonly=True)

        # Iterate file and load items on memory
        with env.begin() as txn:
            cursor = txn.cursor()
            for key, value in cursor:
                key_str = key.decode('ascii')
                if 'label' in key_str:
                    # Get shape information from key name
                    info_key = key_str.split('_')
                    # Get image shape [2:None] means from index 2 to the end
                    shape_img = tuple(map(lambda x: int(x), info_key[2:None]))
                    label_data = np.frombuffer(value, dtype=np.uint8).reshape(shape_img).astype(np.float32)
                    label_data = np.expand_dims(label_data, axis=2)
                    if shape_img != (224,224,1):
                        print('Error on label')
                    self.__ys.append(label_data)
                else:
                    # Get shape information from key name
                    info_key = key_str.split('_')
                    # Get image shape [2:None] means from index 2 to the end
                    shape_img = tuple(map(lambda x: int(x), info_key[2:None]))
                    if shape_img != (224,224,3):
                        print('Error on image')
                    self.__xs.append(np.frombuffer(value, dtype=np.uint8).reshape(shape_img).astype(np.float32))
```

This make me think that could be a problem on my LMDB dataset creation or probably some image inside my dataset is bogus...

**Comment by leonardoaraujosantos** [comment]
The problem was that some images were not RGB, so on those cases I just ignored them
